###############
# Main config #
###############


### Build settings ###

markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap


### Site metadata ###

title: The Buckfever Underground
email: info@toastcoetzer.com
description: Spoken-word experimental rock band in Cape Town, South Africa.

# Repo name, used as path for entire site. This is where the site is hosted on Github Pages but this
# must be configured so that all internal URLs can easily be made relative to this.
baseurl: "/the-buckfever-underground"
# Used if hosting on a custom domain.
url: ""


### Tracking ###

# GA is used for both staging and prod. The filters are set on the GA views to be restrictive on
# those to environments' domains, so will effectively localhost and spam views.
google_analytics: UA-87705880-3
bing:


### Social links ###

facebook_username: TheBuckfeverUnderground
instagram_username: thebuckfeverunderground
twitter_username: the_buckfever
github_repo: MichaelCurrin/the-buckfever-underground
rss: rss


### Content settings ###

# Include posts, shows, etc. dated in the future.
future: true

# For readability of the repo, the top-level pages are their own directory and this allows
# them to be used.
include:
  - '_pages'

# Navigation bar items, in required order.
header_pages:
  - "_pages/about.md"
  - "_pages/shows.md"
  - "_pages/music.md"
  - "_pages/merch.md"
  - "_pages/blog.md"
  - "_pages/press.md"
  - "_pages/contact.md"

# This will create individual pages for each collection item.
collections:
  shows:
    output: true
  music:
    output: true
  press:
    output: true

# Set the layouts. Note that the music directory is set to track layout and then just the albums
# are overridden to use the album layout. Then for press, the index page is the summary and other
# pages are reviews.
defaults:
  - scope:
      path: ""
      type: "press"
    values:
      layout: "press_review"
  - scope:
      path: "*/*/index.md"
      type: "press"
    values:
      layout: "press_main"
  - scope:
      path: ""
      type: "shows"
    values:
      layout: "show"
  - scope:
      path: ""
      type: "music"
    values:
      layout: "track"
  - scope:
      path: "*/*/index.md"
      type: "music"
    values:
      layout: "album"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

# Helper to allow album images to only need to be referenced by filename, as
# this will be prepended on album pages.
album_images_dir: /assets/images/albums/

# Exclude from built results. Dot files and underscore files will excluded already.
exclude:
  - bin
  - vendor
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
