###############
# Main config #
###############


# Site settings.
title: The Buckfever Underground
email: info@toastcoetzer.com
description: Spoken-word experimental rock band in Cape Town, South Africa.

# Require for Github Pages deploy as staging environment.
baseurl: "/the-buckfever-underground"
url: ""

# Album images only need to be referenced by filename as this will be prepended on album pages.
album_images_dir: /assets/images/albums/

# GA is used for both staging and prod. The filters are set on the GA views to be restrictive on
# those to environments' domains, so will effectively localhost and spam views.
google_analytics: UA-87705880-3
bing:

facebook_username: TheBuckfeverUnderground
# Replace template's username with a repo.
github_repo: MichaelCurrin/the-buckfever-underground
twitter_username: the_buckfever
rss: rss


# Build settings.
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
# Include posts, shows, etc. dated in the future.
future: true


exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - script
  - README.md
  - LICENSE


# Keep top-level pages in their own directory.
include:
  - '_pages'

# Nav bar order.
header_pages:
  - "_pages/about.md"
  - "_pages/shows.md"
  - "_pages/music.md"
  - "_pages/merch.md"
  - "_pages/blog.md"
  - "_pages/press.md"
  - "_pages/contact.md"


# Create individual pages for each collection item.
collections:
  shows:
    output: true
  music:
    output: true
  press:
    output: true


# Set the layouts. Note that the music directory is set to track layout and then just the albums
# are overriden to use the album layout. And for press the index page is the summary and other
# pages are reviews.
defaults:
  - scope:
      path: ""
      type: "press"
    values:
      layout: "press_review"
  - scope:
      path: "*/*/index.md"
      type: "press"
    values:
      layout: "press_main"
  - scope:
      path: ""
      type: "shows"
    values:
      layout: "show"
  - scope:
      path: ""
      type: "music"
    values:
      layout: "track"
  - scope:
      path: "*/*/index.md"
      type: "music"
    values:
      layout: "album"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"
