# Site settings
title: The BuckFever Underground
email: info@toastcoetzer.co.za
description: Spoken word over improvised music
baseurl: "thebuckfeverground"
# For RSS and SEO consider setting this as a deploy value. How does it affect Github Pages
# local serving and builds for hosted site?
url: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
