# Site settings
title: The Buckfever Underground
email: info@toastcoetzer.co.za
description: Catch the Buckfever
baseurl: "the-buckfever-underground"
url: ""
facebook_username: TheBuckfeverUnderground
# This is used as the repo path.
github_username: MichaelCurrin/the-buckfever-underground
twitter_username: the_buckfever
rss: rss


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap


# Keep top-level pages in their own directory.
include:
  - '_pages'

# Nav bar order.
header_pages:
  - "_pages/about.md"
  - "_pages/shows.md"
  - "_pages/music.md"
  - "_pages/merch.md"
  - "_pages/blog.md"
  - "_pages/press.md"
  - "_pages/contact.md"


# Create individual pages for each collection item.
collections:
  shows:
    output: true
  music:
    output: true
  press:
    output: true


# Set the layouts. Note that the music directory is set to track layout and then just the albums
# are overriden to use the album layout.
defaults:
  - scope:
      path: ""
      type: "press"
    values:
      layout: "press"
  - scope:
      path: ""
      type: "shows"
    values:
      layout: "show"
  - scope:
      path: ""
      type: "music"
    values:
      layout: "track"
  - scope:
      path: "*/*/index.md"
      type: "music"
    values:
      layout: "album"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"
