[build]
  base = "/"
  publish = "_site"
  command = "jekyll build --config _config.yml"

[context.production]
  environment = {JEKYLL_ENV = "production"}
  command = "jekyll build --config _config.yml _config_prod.yml --baseurl ''"
